name: multivendor_clean_architecture_starter
description: Multivendor starter repository for new project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: 9.2.2
  mvs_widget:
    path: package/mvs_widget
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  bloc: 8.1.4
  bloc_concurrency: 0.2.5
  dependency_initializer: 1.2.0
  flutter_bloc: 8.1.6
  mvs_database:
    path: package/mvs_database
  mvs_rest:
    path: package/mvs_rest
  collection: 1.18.0
  equatable: 2.0.5
  mvs_utility:
    path: package/mvs_utility
  flutter_launcher_icons: 0.14.1
  flutter_native_splash: 2.4.2

dev_dependencies:
  auto_route_generator: 9.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: IconData
      fonts:
        - asset: asset/font/IconData.ttf
  assets:
    - asset/vec/