name: mvs_rest
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.2.6

dependencies:
  dio: 5.7.0
  json_annotation: 4.9.0

dev_dependencies:
  build_runner: 2.4.13
  json_serializable: 6.8.0
  test: 1.25.8
